# @see https://lark.alipay.com/cise/204080374/335151529
# @see https://gitlab.alibaba-inc.com/node/ci
# @see https://gitlab.alibaba-inc.com/node/ci/blob/master/.gitlab-ci.yml
# @see https://groups.alidemo.cn/alife/ci/docs/_book/dev-guide/intro.html
# - rpm -ql nodejs-8.9.1
stage:
  cise-node-8:
    env:
      setting: {}
      image: cise/cise_7u2
    plugin:
      -
        param:
          url: '${repo}'
          branch: '${branch}'
          path: '${source_root}'
        name: checkout
        pos: front
    type: unit_test
    exec:
      - yum install -y -b current nodejs-8.9.1
      - PATH=/opt/taobao/install/node-v8.9.1/bin:$PATH node -v
      - PATH=/opt/taobao/install/node-v8.9.1/bin:$PATH npm install tnpm -g --registry=https://registry.npm.alibaba-inc.com
      - PATH=/opt/taobao/install/node-v8.9.1/bin:$PATH tnpm i
      - "PATH=/opt/taobao/install/node-v8.9.1/bin:$PATH \
        CI_BUILD_REF=$source_version \
        CI_BUILD_REF_NAME=$scm_branch \
        CI_BUILD_REPO=$scm_url \
        CI_BUILD_URL=https://cise.alibaba-inc.com/task/$task_id/build/$build_idx \
        npm run ci"
pipeline:
  - cise-node-8
